Repository MelleD/lovelace-expander-card, pull requests merged in 2025-09, with the labels that each got.

#631 fix: Configuration option typo
  README.md
  src/ExpanderCard.svelte
  src/configtype.ts
Labels: bug

#634 build(deps-dev): bump prettier-plugin-svelte from 3.3.3 to 3.4.0
  package.json
Labels: dependencies

#638 miscellaneous: fix autoClose.yml
  .github/workflows/autoClose.yml
Labels: miscellaneous
